# Generated by Django 2.1.3 on 2018-11-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findWork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Password',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Username',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
