# Generated by Django 2.1.3 on 2018-11-12 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findWork', '0003_administrator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrator',
            old_name='User_ID',
            new_name='User',
        ),
    ]
