# Generated by Django 2.1.3 on 2018-11-13 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findWork', '0006_works'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='Address',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='works',
            name='UserBoss',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Boss', to='findWork.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='works',
            name='UserEmployee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Employees', to='findWork.User'),
            preserve_default=False,
        ),
    ]
