# Generated by Django 2.1.3 on 2018-11-14 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findWork', '0007_auto_20181113_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='UserEmployee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Employee', to='findWork.User'),
        ),
    ]
