# Generated by Django 2.1.3 on 2018-11-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findWork', '0008_auto_20181113_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Phone',
            field=models.CharField(default=9, max_length=30),
            preserve_default=False,
        ),
    ]
