# Generated by Django 2.1.3 on 2018-11-21 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findWork', '0010_auto_20181118_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='Phone',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='applicant',
            name='UserBoss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Boss1', to='findWork.User'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='UserEmployee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Employee1', to='findWork.User'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='WorkID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WorkID', to='findWork.User'),
        ),
    ]
