# Generated by Django 2.1.3 on 2018-11-21 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findWork', '0011_auto_20181120_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='UserBoss',
            new_name='UserBoss1',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='UserEmployee',
            new_name='UserEmployee1',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='WorkID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WorkID', to='findWork.Works'),
        ),
    ]
